export const databases = {
    database1: {
        customer: [
            {
                customerID: "ALFKI",
                companyName: "Alfreds Futterkiste",
                contactName: "Maria Anders",
                contactTitle: "Sales Representative",
                address: "Obere Str. 57",
                city: "Berlin",
                region: "NULL",
                postalCode: "12209",
                country: "Germany",
                phone: "030-0074321",
                fax: "030-0076545",
            },
            {
                customerID: "ANATR",
                companyName: "Ana Trujillo Emparedados y helados",
                contactName: "Ana Trujillo",
                contactTitle: "Owner",
                address: "Avda. de la Constitución 2222",
                city: "México D.F.",
                region: "NULL",
                postalCode: "05021",
                country: "Mexico",
                phone: "(5) 555-4729",
                fax: "(5) 555-3745",
            },
            {
                customerID: "ANTON",
                companyName: "Antonio Moreno Taquería",
                contactName: "Antonio Moreno",
                contactTitle: "Owner",
                address: "Mataderos  2312",
                city: "México D.F.",
                region: "NULL",
                postalCode: "05023",
                country: "Mexico",
                phone: "(5) 555-3932",
                fax: "NULL",
            },
            {
                customerID: "AROUT",
                companyName: "Around the Horn",
                contactName: "Thomas Hardy",
                contactTitle: "Sales Representative",
                address: "120 Hanover Sq.",
                city: "London",
                region: "NULL",
                postalCode: "WA1 1DP",
                country: "UK",
                phone: "(171) 555-7788",
                fax: "(171) 555-6750",
            },
            {
                customerID: "BERGS",
                companyName: "Berglunds snabbköp",
                contactName: "Christina Berglund",
                contactTitle: "Order Administrator",
                address: "Berguvsvägen  8",
                city: "Luleå",
                region: "NULL",
                postalCode: "S-958 22",
                country: "Sweden",
                phone: "0921-12 34 65",
                fax: "0921-12 34 67",
            },
            {
                customerID: "BLAUS",
                companyName: "Blauer See Delikatessen",
                contactName: "Hanna Moos",
                contactTitle: "Sales Representative",
                address: "Forsterstr. 57",
                city: "Mannheim",
                region: "NULL",
                postalCode: "68306",
                country: "Germany",
                phone: "0621-08460",
                fax: "0621-08924",
            },
            {
                customerID: "BLONP",
                companyName: "Blondesddsl père et fils",
                contactName: "Frédérique Citeaux",
                contactTitle: "Marketing Manager",
                address: "24 place Kléber",
                city: "Strasbourg",
                region: "NULL",
                postalCode: "67000",
                country: "France",
                phone: "88.60.15.31",
                fax: "88.60.15.32",
            },
            {
                customerID: "BOLID",
                companyName: "Bólido Comidas preparadas",
                contactName: "Martín Sommer",
                contactTitle: "Owner",
                address: "67C Araquil",
                city: "Madrid",
                region: "NULL",
                postalCode: "28023",
                country: "Spain",
                phone: "(91) 555 22 82",
                fax: "(91) 555 91 99",
            },
            {
                customerID: "BONAP",
                companyName: "Bon app'",
                contactName: "Laurence Lebihan",
                contactTitle: "Owner",
                address: "12 rue des Bouchers",
                city: "Marseille",
                region: "NULL",
                postalCode: "13008",
                country: "France",
                phone: "91.24.45.40",
                fax: "91.24.45.41",
            },
        ],
        product: [
            {
                productID: "1",
                productName: "Chai",
                supplierID: "1",
                categoryID: "1",
                quantityPerUnit: "10 boxes x 20 bags",
                unitPrice: "18.00",
                unitsInStock: "39",
                unitsOnOrder: "0",
                reorderLevel: "10",
                discontinued: "0",
            },
            {
                productID: "2",
                productName: "Chang",
                supplierID: "1",
                categoryID: "1",
                quantityPerUnit: "24 - 12 oz bottles",
                unitPrice: "19.00",
                unitsInStock: "17",
                unitsOnOrder: "40",
                reorderLevel: "25",
                discontinued: "0",
            },
            {
                productID: "3",
                productName: "Aniseed Syrup",
                supplierID: "1",
                categoryID: "2",
                quantityPerUnit: "12 - 550 ml bottles",
                unitPrice: "10.00",
                unitsInStock: "13",
                unitsOnOrder: "70",
                reorderLevel: "25",
                discontinued: "0",
            },
            {
                productID: "4",
                productName: "Chef Anton's Cajun Seasoning",
                supplierID: "2",
                categoryID: "2",
                quantityPerUnit: "48 - 6 oz jars",
                unitPrice: "22.00",
                unitsInStock: "53",
                unitsOnOrder: "0",
                reorderLevel: "0",
                discontinued: "0",
            },
            {
                productID: "5",
                productName: "Chef Anton's Gumbo Mix",
                supplierID: "2",
                categoryID: "2",
                quantityPerUnit: "36 boxes",
                unitPrice: "21.35",
                unitsInStock: "0",
                unitsOnOrder: "0",
                reorderLevel: "0",
                discontinued: "1",
            },
            {
                productID: "6",
                productName: "Grandma's Boysenberry Spread",
                supplierID: "3",
                categoryID: "2",
                quantityPerUnit: "12 - 8 oz jars",
                unitPrice: "25.00",
                unitsInStock: "120",
                unitsOnOrder: "0",
                reorderLevel: "25",
                discontinued: "0",
            },
            {
                productID: "7",
                productName: "Uncle Bob's Organic Dried Pears",
                supplierID: "3",
                categoryID: "7",
                quantityPerUnit: "12 - 1 lb pkgs.",
                unitPrice: "30.00",
                unitsInStock: "15",
                unitsOnOrder: "0",
                reorderLevel: "10",
                discontinued: "0",
            },
            {
                productID: "8",
                productName: "Northwoods Cranberry Sauce",
                supplierID: "3",
                categoryID: "2",
                quantityPerUnit: "12 - 12 oz jars",
                unitPrice: "40.00",
                unitsInStock: "6",
                unitsOnOrder: "0",
                reorderLevel: "0",
                discontinued: "0",
            },
            {
                productID: "9",
                productName: "Mishi Kobe Niku",
                supplierID: "4",
                categoryID: "6",
                quantityPerUnit: "18 - 500 g pkgs.",
                unitPrice: "97.00",
                unitsInStock: "29",
                unitsOnOrder: "0",
                reorderLevel: "0",
                discontinued: "1",
            },
            {
                productID: "10",
                productName: "Ikura",
                supplierID: "4",
                categoryID: "8",
                quantityPerUnit: "12 - 200 ml jars",
                unitPrice: "31.00",
                unitsInStock: "31",
                unitsOnOrder: "0",
                reorderLevel: "0",
                discontinued: "0",
            },
            {
                productID: "11",
                productName: "Queso Cabrales",
                supplierID: "5",
                categoryID: "4",
                quantityPerUnit: "1 kg pkg.",
                unitPrice: "21.00",
                unitsInStock: "22",
                unitsOnOrder: "30",
                reorderLevel: "30",
                discontinued: "0",
            },
        ],
    },
    database2: {
        place: [
            {
                territoryID: "01581",
                territoryDescription: "Westboro",
                regionID: "1",
            },
            {
                territoryID: "01730",
                territoryDescription: "Bedford",
                regionID: "1",
            },
            {
                territoryID: "01833",
                territoryDescription: "Georgetow",
                regionID: "1",
            },
            {
                territoryID: "02116",
                territoryDescription: "Boston",
                regionID: "1",
            },
            {
                territoryID: "02139",
                territoryDescription: "Cambridge",
                regionID: "1",
            },
            {
                territoryID: "02184",
                territoryDescription: "Braintree",
                regionID: "1",
            },
            {
                territoryID: "02903",
                territoryDescription: "Providence",
                regionID: "1",
            },
            {
                territoryID: "03049",
                territoryDescription: "Hollis",
                regionID: "3",
            },
            {
                territoryID: "03801",
                territoryDescription: "Portsmouth",
                regionID: "3",
            },
            {
                territoryID: "06897",
                territoryDescription: "Wilton",
                regionID: "1",
            },
            {
                territoryID: "07960",
                territoryDescription: "Morristown",
                regionID: "1",
            },
            {
                territoryID: "08837",
                territoryDescription: "Edison",
                regionID: "1",
            },
            {
                territoryID: "10019",
                territoryDescription: "NewYork",
                regionID: "1",
            },
            {
                territoryID: "10038",
                territoryDescription: "NewYork",
                regionID: "1",
            },
            {
                territoryID: "11747",
                territoryDescription: "Mellvile",
                regionID: "1",
            },
            {
                territoryID: "14450",
                territoryDescription: "Fairport",
                regionID: "1",
            },
            {
                territoryID: "19428",
                territoryDescription: "Philadelphia",
                regionID: "3",
            },
            {
                territoryID: "19713",
                territoryDescription: "Neward",
                regionID: "1",
            },
            {
                territoryID: "20852",
                territoryDescription: "Rockville",
                regionID: "1",
            },
            {
                territoryID: "27403",
                territoryDescription: "Greensboro",
                regionID: "1",
            },
            {
                territoryID: "27511",
                territoryDescription: "Cary",
                regionID: "1",
            },
            {
                territoryID: "29202",
                territoryDescription: "Columbia",
                regionID: "4",
            },
            {
                territoryID: "30346",
                territoryDescription: "Atlanta",
                regionID: "4",
            },
            {
                territoryID: "31406",
                territoryDescription: "Savannah",
                regionID: "4",
            },
            {
                territoryID: "32859",
                territoryDescription: "Orlando",
                regionID: "4",
            },
            {
                territoryID: "33607",
                territoryDescription: "Tampa",
                regionID: "4",
            },
            {
                territoryID: "40222",
                territoryDescription: "Louisville",
                regionID: "1",
            },
            {
                territoryID: "44122",
                territoryDescription: "Beachwood",
                regionID: "3",
            },
            {
                territoryID: "45839",
                territoryDescription: "Findlay",
                regionID: "3",
            },
            {
                territoryID: "48075",
                territoryDescription: "Southfield",
                regionID: "3",
            },
            {
                territoryID: "48084",
                territoryDescription: "Troy",
                regionID: "3",
            },
            {
                territoryID: "48304",
                territoryDescription: "BloomfieldHills",
                regionID: "3",
            },
            {
                territoryID: "53404",
                territoryDescription: "Racine",
                regionID: "3",
            },
            {
                territoryID: "55113",
                territoryDescription: "Roseville",
                regionID: "3",
            },
            {
                territoryID: "55439",
                territoryDescription: "Minneapolis",
                regionID: "3",
            },
            {
                territoryID: "60179",
                territoryDescription: "HoffmanEstates",
                regionID: "2",
            },
            {
                territoryID: "60601",
                territoryDescription: "Chicago",
                regionID: "2",
            },
            {
                territoryID: "72716",
                territoryDescription: "Bentonville",
                regionID: "4",
            },
            {
                territoryID: "75234",
                territoryDescription: "Dallas",
                regionID: "4",
            },
            {
                territoryID: "78759",
                territoryDescription: "Austin",
                regionID: "4",
            },
            {
                territoryID: "80202",
                territoryDescription: "Denver",
                regionID: "2",
            },
            {
                territoryID: "80909",
                territoryDescription: "ColoradoSprings",
                regionID: "2",
            },
            {
                territoryID: "85014",
                territoryDescription: "Phoenix",
                regionID: "2",
            },
            {
                territoryID: "85251",
                territoryDescription: "Scottsdale",
                regionID: "2",
            },
            {
                territoryID: "90405",
                territoryDescription: "SantaMonica",
                regionID: "2",
            },
            {
                territoryID: "94025",
                territoryDescription: "MenloPark",
                regionID: "2",
            },
            {
                territoryID: "94105",
                territoryDescription: "SanFrancisco",
                regionID: "2",
            },
            {
                territoryID: "95008",
                territoryDescription: "Campbell",
                regionID: "2",
            },
            {
                territoryID: "95054",
                territoryDescription: "SantaClara",
                regionID: "2",
            },
            {
                territoryID: "95060",
                territoryDescription: "SantaCruz",
                regionID: "2",
            },
            {
                territoryID: "98004",
                territoryDescription: "Bellevue",
                regionID: "2",
            },
            {
                territoryID: "98052",
                territoryDescription: "Redmond",
                regionID: "2",
            },
            {
                territoryID: "98104",
                territoryDescription: "Seattle",
                regionID: "2",
            },
        ],
    },
};
